name: Generate default project
on:
  push:

jobs:
  test-Github-default-instance:
    uses: ./.github/workflows/generate_default_project_reusable.yaml
    with:
      repo-path: "github.com/karllu3/ds-lk-default.git"
      repo-user: karllu3
      repo-email: lukasz.karlowski@deepsense.ai
      cookiecutter-profile: cookiecutter_default_gh.yaml
    secrets:
      token: ${{ secrets.REPO_KEY_GITHUB }}

  test-GitLab-default-instance:
    uses: ./.github/workflows/generate_default_project_reusable.yaml
    with:
      repo-path: "gitlab.com/lukasz.karlowski/ds-lk-default.git"
      repo-user: lukasz karlowski
      repo-email: lukasz.karlowski@deepsense.ai
      cookiecutter-profile: cookiecutter_default_gh.yaml
    secrets:
      token: ${{ secrets.REPO_KEY_GITLAB }}
