name: Template check

on:
  push:

jobs:

  validate-default-gh-instance:
    runs-on: ubuntu-latest
    container: python:3.11
    permissions:
      contents: read
      pages: write
    env:
      GH_TEST_REPO_TOKEN: ${{ secrets.REPO_KEY_GITLAB }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create  Github project instance
        run: cookiecutter . --no-input --config-file cookiecutter_default_gh.yaml

      - name: Remote checkout
        run: git clone https://oauth2:${{ secrets.REPO_KEY_GITLAB }}@github.com/karllu3/ds-lk-default.git ds-gh-default2

      - name: Set safe directory
        run: |
          git config --global --add safe.directory /__w/ds-template/ds-template

      - name: cp repo
        run:
          cp -r ds-gh-default/. ds-gh-default2

      - name: ls repo
        run:
          ls -al ds-gh-default2

      - name: Prepare git5
        working-directory: ./ds-gh-default2
        run: |
          git config --local user.email "lukasz.karlowski@deepsense.ai"
          git config --local user.name "lukasz karlowski"
          git checkout -b ds-default-check
          git add .

      - name: Validate package build
        working-directory: ./ds-gh-default2
        run: |
          python -m pip install .

      - name: Install pre-commit
        run: pip3 install pre-commit

      - name: Run pre-commit checks
        working-directory: ./ds-gh-default2
        run: pre-commit run --all-files --show-diff-on-failure --color always

      - name: Push repo
        working-directory: ./ds-gh-default2
        run: |
          git commit -m "Repo after creation"
          git push --set-upstream origin ds-default-check -f
          
